# Generated by Django 3.2.9 on 2021-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(help_text='Name of the Emotion', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='occasion',
            field=models.DateField(help_text='Date the entry was made', verbose_name='Occasion'),
        ),
    ]
