# Generated by Django 3.2.9 on 2021-11-26 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='Title of the Project', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.TextField(blank=True, help_text='Description of the Project', max_length=2000, verbose_name='Description')),
                ('owner', models.ForeignKey(blank=True, help_text='Owned by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('title',),
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='Title of the Task', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.TextField(blank=True, help_text='Description of the Task', max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('planned', 'Task is planned'), ('started', 'Task is started'), ('hold', 'Task is on hold'), ('finished', 'Task is finished')], default='planned', help_text='State of the task', max_length=100, verbose_name='State')),
                ('project', models.ForeignKey(help_text='Task belongs to project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timekeeping.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('project', 'title'),
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('allowed', models.BooleanField(default=True, help_text='Logging Work is allowed', verbose_name='Allowed')),
                ('max_workload', models.DurationField(default=0, help_text='Max workload in time. If left zero no workload cap.', verbose_name='Maximum Workload')),
                ('task', models.ForeignKey(help_text='Task of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timekeeping.task')),
                ('user', models.ForeignKey(help_text='User of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ('task', 'user'),
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('start', models.DateTimeField(blank=True, help_text='Datetime when the work was started', null=True, verbose_name='Started at')),
                ('stop', models.DateTimeField(blank=True, help_text='Datetime when the work was stopped', null=True, verbose_name='Ended on')),
                ('time', models.DurationField(blank=True, help_text='Log manual time', null=True, verbose_name='Manual Time')),
                ('notes', models.TextField(blank=True, help_text='Notes / References for the log', max_length=2000, verbose_name='Notes')),
                ('assignment', models.ForeignKey(help_text='Worklog for assignments', on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='timekeeping.assignment')),
            ],
            options={
                'verbose_name': 'Worklog',
                'verbose_name_plural': 'Worklog',
                'ordering': ('start', 'stop', 'time'),
                'unique_together': {('assignment', 'created_at')},
            },
        ),
    ]
