# Generated by Django 3.2.9 on 2021-11-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(blank=True, help_text='Title of the Project', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.CharField(blank=True, help_text='Description of the Project', max_length=2000, verbose_name='Description')),
                ('owner', models.ForeignKey(blank=True, help_text='Owned by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(blank=True, help_text='Title of the Task', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.CharField(blank=True, help_text='Description of the Task', max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('planned', 'Task is planned'), ('started', 'Task is started'), ('hold', 'Task is on hold'), ('finished', 'Task is finished')], default='planned', help_text='State of the task', max_length=100, verbose_name='State')),
                ('project', models.ForeignKey(blank=True, help_text='Task belongs to project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timekeeping.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
