# Generated by Django 3.2.9 on 2021-11-26 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timekeeping.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='Title of the Project', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.TextField(blank=True, help_text='Description of the Project', max_length=2000, verbose_name='Description')),
                ('owner', models.ForeignKey(blank=True, help_text='Owned by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('title',),
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='Title of the Task', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Unique Slug Identifier')),
                ('description', models.TextField(blank=True, help_text='Description of the Task', max_length=2000, verbose_name='Description')),
                ('status', models.CharField(choices=[('planned', 'Task is planned'), ('started', 'Task is started'), ('hold', 'Task is on hold'), ('finished', 'Task is finished')], default='started', help_text='State of the task', max_length=100, verbose_name='State')),
                ('project', models.ForeignKey(help_text='Task belongs to project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timekeeping.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('project', 'title'),
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('allowed', models.BooleanField(default=True, help_text='Logging Work is allowed', verbose_name='Allowed')),
                ('max_workload', models.DurationField(default=0, help_text='Max workload in time. If left zero no workload cap.', verbose_name='Maximum Workload')),
                ('current_workload', models.DurationField(blank=True, help_text='Work currently logged on this assignment', null=True, verbose_name='Current Workload')),
                ('current_log', models.JSONField(default=timekeeping.models.get_current_log_default_json, help_text='', verbose_name='Current Log')),
                ('archived_log', models.JSONField(default=timekeeping.models.get_archive_log_list_json, help_text='', verbose_name='Archived Logs')),
                ('task', models.ForeignKey(help_text='Task of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timekeeping.task')),
                ('user', models.ForeignKey(help_text='User of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ('task', 'user'),
                'unique_together': {('user', 'task')},
            },
        ),
    ]
