# Generated by Django 3.2.9 on 2021-11-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='slug',
        ),
        migrations.AddField(
            model_name='worklog',
            name='completed',
            field=models.BooleanField(default=False, help_text='The worklog instance is completed.', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'Task is planned'), ('started', 'Task is started'), ('hold', 'Task is on hold'), ('finished', 'Task is finished')], default='started', help_text='State of the task', max_length=100, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('allowed', models.BooleanField(default=True, help_text='Logging Work is allowed', verbose_name='Allowed')),
                ('max_workload', models.DurationField(default=0, help_text='Max workload in time. If left zero no workload cap.', verbose_name='Maximum Workload')),
                ('current_workload', models.DurationField(default=0, help_text='Work currently logged on this assignment', verbose_name='Current Workload')),
                ('task', models.ForeignKey(help_text='Task of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timekeeping.task')),
                ('user', models.ForeignKey(help_text='User of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ('task', 'user'),
                'unique_together': {('user', 'task')},
            },
        ),
        migrations.AlterField(
            model_name='worklog',
            name='assignment',
            field=models.ForeignKey(help_text='Worklog for assignments', on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='timekeeping.taskassignment'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
