# Generated by Django 3.2.9 on 2021-11-26 16:07

import datetime
from django.db import migrations, models
import timekeeping.models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='archived_log',
            field=models.JSONField(default=timekeeping.models.get_archive_log_list_json, help_text='', verbose_name='Archived Logs'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='current_log',
            field=models.JSONField(default=timekeeping.models.get_current_log_default_json, help_text='', verbose_name='Current Log'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='current_workload',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Work currently logged on this assignment', verbose_name='Current Workload'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='max_workload',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Max workload in time. If left zero no workload cap.', verbose_name='Maximum Workload'),
        ),
    ]
