# Generated by Django 3.2.9 on 2021-11-23 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('project', 'title'), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Project', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title of the Project', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Task', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='Task belongs to project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timekeeping.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Title of the Task', max_length=255, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('allowed', models.BooleanField(default=True, help_text='Logging Work is allowed', verbose_name='Allowed')),
                ('max_workload', models.PositiveSmallIntegerField(default=0, help_text='Max workload in hours. 0 is unlimited hours', verbose_name='Maximum Workload')),
                ('task', models.ForeignKey(help_text='Task of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timekeeping.task')),
                ('user', models.ForeignKey(help_text='User of assignment', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ('task', 'user'),
            },
        ),
    ]
