# Generated by Django 3.2.9 on 2021-11-23 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0002_auto_20211123_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start', models.DateTimeField(blank=True, help_text='Datetime when the work was started', verbose_name='Started at')),
                ('stop', models.DateTimeField(blank=True, help_text='Datetime when the work was stopped', verbose_name='Ended on')),
                ('time', models.DurationField(help_text='Log manual time', verbose_name='Manual Time')),
                ('notes', models.TextField(blank=True, help_text='Notes / References for the log', max_length=2000, verbose_name='Notes')),
                ('assignment', models.ForeignKey(help_text='Worklog for assignments', on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='timekeeping.assignment')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ('start', 'stop', 'time'),
            },
        ),
    ]
