# Generated by Django 3.2.9 on 2021-11-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0004_auto_20211123_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Datetime when the work was started', null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='stop',
            field=models.DateTimeField(blank=True, help_text='Datetime when the work was stopped', null=True, verbose_name='Ended on'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='time',
            field=models.DurationField(blank=True, help_text='Log manual time', null=True, verbose_name='Manual Time'),
        ),
    ]
