# Generated by Django 3.2.9 on 2021-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timekeeping', '0005_auto_20211123_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_workload',
            field=models.DurationField(default=0, help_text='Max workload in hours. If left zero no workload cap.', verbose_name='Maximum Workload'),
        ),
    ]
